### ISSUE TITLE
Can AttributeAnnotations set `__parent__`?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.annotation#11]
This would make it compatible with the `IConnection` adapter provided by `zope.keyreference` (assuming the object it annotates is persistent), which could simplify some use cases. AttributeAnnotations is itself not persistent, though the BTree it contains is.

For pickle compatibility this could be a property that reads `self.obj`.

Are there any downsides to making this generally the case?

(This comes out of a discussion in  a private repository.)

**Comment by jamadden** [comment]
I'll note that [zope.principalannotation](https://github.com/zopefoundation/zope.principalannotation/blob/py36/src/zope/principalannotation/utility.py#L58) does this by default.

**Comment by icemac** [comment]
> I'll note that [zope.principalannotation](https://github.com/zopefoundation/zope.principalannotation/blob/master/src/zope/principalannotation/utility.py#L58) does this by default.

But the `Annotations` object used there is a subclass of `Persistent` and `Location`.

I am not sure what you want to change. Could you sketch it on a branch? I think it is much easier to think about existing code.

**Comment by jamadden** [comment]
Sure, #13. It's very simple, it isn't even a new field.

**Comment by icemac** [comment]
I did not think it was that easy, but a line of code tells more than a hundred words. :-)
